# Generated by Django 5.1.6 on 2025-02-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='asset',
            name='unique_account_asset_type',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='type',
            new_name='asset_type',
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(fields=('account', 'asset_type'), name='unique_account_asset_asset_type'),
        ),
    ]
